apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yarn-nodemanager
  namespace: applog
spec:
  selector:
    matchLabels:
      app: hadoop 
      role: nodemanager 
  serviceName: "nodemanager"
  replicas: 2
  template:
    metadata:
      labels:
        app: hadoop 
        role: nodemanager
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: nodemanager
        image: custom-hadoop:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8042
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "400m"
        volumeMounts:
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop
        env:
        - name: HADOOP_CONF_DIR
          value: /opt/hadoop/etc/hadoop
        command: ["/entrypoint.sh"]
      volumes:
      - name: hadoop-config-volume
        configMap: 
          name: hadoop-config
  volumeClaimTemplates:
  - metadata:
      name: nodemanager-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
--- 
apiVersion: v1
kind: Service
metadata:
  name: nodemanager
  namespace: applog
spec:
  selector:
    app: hadoop
    role: nodemanager
  ports:
  - protocol: TCP
    port: 8042
    targetPort: 8042