apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-hadoop-pvc
  namespace: applog
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
