apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarn-resourcemanager
  namespace: applog
spec:
  selector:
    matchLabels:
      app: hadoop
      role: resourcemanager 
  template:
    metadata:
      labels:
        app: hadoop 
        role: resourcemanager
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: resourcemanager 
        image: custom-hadoop:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8088  # RM UI
          - containerPort: 8032  # RPC
          - containerPort: 8030  # Scheduler
          - containerPort: 8031  # ResourceManager
          - containerPort: 8033
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "400m"
        volumeMounts:
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop
        env:
        - name: HADOOP_CONF_DIR
          value: /opt/hadoop/etc/hadoop
        command: ["/entrypoint.sh"]
      volumes:
      - name: hadoop-config-volume
        configMap: 
          name: hadoop-config
--- 
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
  namespace: applog
spec:
  selector:
    app: hadoop 
    role: resourcemanager
  ports:
  - port: 8032
    name: resourcemanager-rpc
    targetPort: 8032
    protocol: TCP
  - port: 8030
    name: resourcemanager-scheduler
    targetPort: 8030
    protocol: TCP
  - port: 8031
    name: resource-tracker
    targetPort: 8031
    protocol: TCP
  - port: 8033
    name: admin
    targetPort: 8033
    protocol: TCP
