apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-secondarynamenode
  namespace: applog
spec:
  selector:
    matchLabels:
      app: hadoop 
      role: secondarynamenode
  serviceName: "secondarynamenode"
  replicas: 1
  template:
    metadata:
      labels:
        app: hadoop
        role: secondarynamenode
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-chown
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /hadoop/dfs/secondary"]
        volumeMounts:
        - name: datanode-storage
          mountPath: /hadoop/dfs/secondary
      containers:
      - name: secondarynamenode
        image: custom-hadoop:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50090
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
        resources:
          requests:
            memory: "128Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        volumeMounts:
        - name: secondarynamenode-storage
          mountPath: /hadoop/dfs/secondary
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop
        env:
        - name: HADOOP_CONF_DIR
          value: /opt/hadoop/etc/hadoop
        command: ["/entrypoint.sh"]
      volumes:
      - name: hadoop-config-volume
        configMap: 
          name: hadoop-config
  volumeClaimTemplates:
  - metadata:
      name: secondarynamenode-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
