apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: applog
spec:
  selector:
    app: hadoop
    role: namenode
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: applog
spec:
  selector:
    app: hadoop 
    role: datanode
  ports:
  - port: 50010
    targetPort: 50010
    protocol: TCP

--- 
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
  namespace: applog
spec:
  selector:
    app: hadoop 
    role: resourcemanager
  ports:
  - port: 8032
    name: resourcemanager-rpc
    targetPort: 8032
    protocol: TCP
  - port: 8030
    name: resourcemanager-scheduler
    targetPort: 8030
    protocol: TCP
  - port: 8031
    name: resource-tracker
    targetPort: 8031
    protocol: TCP
  - port: 8033
    name: admin
    targetPort: 8033
    protocol: TCP

--- 
apiVersion: v1
kind: Service
metadata:
  name: nodemanager
  namespace: applog
spec:
  selector:
    app: hadoop
    role: nodemanager
  ports:
  - protocol: TCP
    port: 8042
    targetPort: 8042