apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer-test
  namespace: applog
spec:
  containers:
  - name: kafka-producer
    image: bitnami/kafka:3.6.0
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "300m"
    command:
      - sh
      - -c
      - |
        echo "test message from producer" | kafka-console-producer.sh --bootstrap-server kafka:9092 --topic test-topic && sleep 3600
