apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: kafka-to-hdfs-stream
  namespace: applog
spec:
  type: Python
  mode: cluster
  image: custom-spark:latest
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/app/streaming_process.py"
  sparkVersion: "3.5.5"
  restartPolicy:
    type: Never
  driver: 
    cores: 1
    memory: "1g"
    serviceAccount: spark 
    labels:
      version: 3.5.5
    volumeMounts: 
      - name: app-volume
        mountPath: /opt/spark/app 
  executor:
    cores: 1
    instances: 2
    memory: "1g"
    labels: 
      version: 3.5.5 
    volumeMounts: 
      - name: app-volume
        mountPath: /opt/spark/app
  volumes:
    - name: app-volume
      configMap: 
        name: spark-streaming-job