apiVersion: apps/v1
kind: Deployment
metadata:
  name: sim-log-generator
  namespace: applog
spec:
  replicas: 1  # giả lập 5 máy gửi log
  selector:
    matchLabels:
      app: application
      role: sim-log-generator
  template:
    metadata:
      labels:
        app: application
        role: sim-log-generator
    spec:
      containers:
      - name: sim-log-generator
        image: sim-app:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: sim-config
          mountPath: /etc/sim-config   # nơi để file config
          readOnly: true
      volumes:
      - name: sim-config
        configMap:
          name: sim-config
